# Generated by Django 3.2.5 on 2021-07-25 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='area_de_atuacao',
            field=models.CharField(default='n/a', max_length=140),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='professor',
            name='formacao',
            field=models.CharField(default='n/a', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='professor',
            name='nome_professor',
            field=models.CharField(default='n/a', max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='professor',
            name='tempo_de_experiencia_em_anos',
            field=models.CharField(default='n/a', max_length=3),
            preserve_default=False,
        ),
    ]
